CREATE TABLE STUDENT
(
    ID          INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    CARD_NUMBER VARCHAR(255) UNIQUE NOT NULL ,
    FIRST_NAME  VARCHAR(255),
    SECOND_NAME VARCHAR(255),
    COURSE      INT,
    FACULTY     VARCHAR(255)
);
